### ISSUE TITLE
Consider referencing other / newer obfuscation tools

### ISSUE THREAD

**Issue by truist** [nowsecure/secure-mobile-development#26]
In "Code Complexity and Obfuscation" you provide links to a few obfuscation tools. I work for [PreEmptive Solutions](https://www.preemptive.com/) and we have forked two of those products (iOS Class Guard and LLVM-Obfuscator), and we also provide tools for other platforms ([Dotfuscator](https://www.preemptive.com/products/dotfuscator/overview) for .NET and [DashO](https://www.preemptive.com/products/dasho/overview) for Java). 

In the specific case of iOS Class Guard, [our fork (called PPiOS-Rename)](https://github.com/preemptive/PPiOS-Rename) is meant to provide support for newer versions of Xcode that they don't seem to be supporting - and we significantly improved the product overall. Our fork is open-source and free, so you might want to link to it instead of (or in addition to) iOS Class Guard.

[Our fork of LLVM-Obfuscator (called PPiOS-ControlFlow)](https://www.preemptive.com/products/ppios) is not open-source (or free), but it also brings support up to date with the latest Xcode, and provides enhancements/improvements.

On the .NET platform, Dotfuscator has a [Community Edition](https://www.preemptive.com/products/dotfuscator/compare-editions) that is included "in the box" with Visual Studio, and is free. For someone looking for a free solution on that platform, you might want to link to it, also.

Finally, since you link to DexGuard, I thought you might also want to link to DashO.

If you're open to these changes, I'd be happy to create a pull request for them; I thought it best to check if you want them, first.

Thanks! (And thanks for the great guide!)

**Comment by dweinstein** [comment]
hey @truist... can you open a PR so we could take a look? In general I think we'd like to avoid favoring any one tool or vendor

**Comment by truist** [comment]
Will do!
