### ISSUE TITLE
PermissionsDispatcher

### ISSUE THREAD

**Issue by dweinstein** [nowsecure/secure-mobile-development#36]
PermissionsDispatcher is an awesome tool for managing Android Runtime Permissions in apps via Java annotations/decorators.

mentioned it here for the secure dev talk... https://www.nowsecure.com/blog/2016/08/24/android-buckles-ios-opens-trends-platform-security-affecting-developers/

**Comment by sbakken** [comment]
Pending decisions about where this fits and/or whether it requires a new best practice

**Comment by sbakken** [comment]
Relevant to a "don't over-permission your apps" best practice.

**Comment by sbakken** [comment]
https://github.com/nowsecure/secure-mobile-development/pull/67 takes care of this.
