### ISSUE TITLE
Add entry on use of NSSecureCoding

### ISSUE THREAD

**Issue by dweinstein** [nowsecure/secure-mobile-development#9]
references:
- http://nshipster.com/nssecurecoding/
-  http://mjtsai.com/blog/2015/11/08/the-java-deserialization-bug-and-nssecurecoding/

(update w/ more refs later)

**Comment by dweinstein** [comment]
this would be a (new for us) best practice to be cautious when deserializing data from an untrusted source. this falls under MITRE CWE [502](https://cwe.mitre.org/data/definitions/502.html) and applies to both Android (particularly when talking about Binder operations) and iOS as mentioned in the comment.

**Comment by dweinstein** [comment]
the best practice might be called, e.g., Use caution deserializing untrusted data

**Comment by sbakken** [comment]
Addressed with PR: https://github.com/nowsecure/secure-mobile-development/pull/72.
